---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Store-DBIx-DataModel
no_index:
  directory:
    - inc
    - t
provides:
  Catalyst::Authentication::Realm::SimpleDB:
    file: lib/Catalyst/Authentication/Realm/SimpleDB.pm
requires:
  Catalyst::Model::DBIDM: 0
  Catalyst::Plugin::Authentication: 0.10008
  Catalyst::Runtime: 5.8
  DBIx::DataModel: 0
  List::MoreUtils: 0
  Moose: 0
  Try::Tiny: 0
  namespace::autoclean: 0
  perl: 5.8.1
resources:
  repository: git@github.com:bokutin/Catalyst-Authentication-Store-DBIx-DateModel.git
version: 0.01
